### ISSUE TITLE
MonadReader broken?

### ISSUE THREAD

**Issue by mikeplus64** [Bodigrim/logict#1]
Per https://hub.darcs.net/dolio/logict/issue/5 `runReader (observeAllT (local (5+) ask)) 0` evaluates to `[0]` instead of `[5]`. Is this intended?

This tiny patch https://hub.darcs.net/mikeplus64/logict/patch/0d1f3bd29c4e1d1f6e285eb6f812b4f58c435681 fixes it.

**Comment by Bodigrim** [comment]
Could you please prepare a PR?

**Comment by Bodigrim** [comment]
Just copy-pasting your patch from darcs for future references:

```diff
-local f m = LogicT $ \sk fk -> unLogicT m ((local f .) . sk) (local f fk)
+local f m = LogicT (\sk fk -> local f (unLogicT m sk fk))
```

**Comment by b-mehta** [comment]
I'm not convinced this is the correct resolution. Taking
```
foo :: MonadReader Int m => m (Int,Int)
foo = do
  x <- local (5+) ask
  y <- ask
  return (x,y)
```
we have `runReader (observeT foo) 0` evaluates to `(5,5)`; i.e. `local` is not actually local. (In contrast, `runReader foo 0` evaluates to `(5,0)`.

I don't have a solution, except to offer that my initial guess of 
```
local f m = m >>= lift . local f . return
```
doesn't work either.

**Comment by Bodigrim** [comment]
@b-mehta This is very worrying, thanks for noticing. It sounds a bit similar to the issue with `MonadLogic (ReaderT e m)`: https://github.com/Bodigrim/logict/blob/c9dbc832857c99136a7d08e951e20993f297396b/Control/Monad/Logic/Class.hs#L110-L118

---

At this point we need to go more formal, talking about laws instead of expectations. Was the old behaviour violating [laws](https://github.com/Bodigrim/logict/blob/c9dbc832857c99136a7d08e951e20993f297396b/Control/Monad/Logic/Class.hs#L28) of `MonadLogic`? Is the new behaviour violating laws of `MonadLogic`? 

Same questions should be asked about laws of `MonadReader`, but none are present in haddocks. For the purpose of this discussion we can use https://github.com/haskell/mtl/issues/5

Unfortunately, I am busy these weeks to dig further.

@sergv @feuerbach you might be interested.

**Comment by sergv** [comment]
I think we're struggling with CPS encoding used in LogicT here. I think the way local is done for `ContT` should work here as well: http://hackage.haskell.org/package/transformers-0.5.6.2/docs/src/Control.Monad.Trans.Cont.html#liftLocal

I.e.
```haskell
local f (LocalT m) = LocalT $ \sk fk -> do
  env <- ask
  local f $ m (local (const env) . sk) (local (const env) . fk)
```

**Comment by b-mehta** [comment]
Nice, this satisfies both requirements (once modified to typecheck):

```haskell
local f (LogicT m) = LogicT $ \sk fk -> do
  env <- ask
  local f $ m ((local (const env) .) . sk) (local (const env) fk)
```

**Comment by Bodigrim** [comment]
Thanks @sergv!
