### ISSUE TITLE
Version 0.7.1.0 is deprecated on Hackage

### ISSUE THREAD

**Issue by kquick** [Bodigrim/logict#20]
For some reason, the (currently) latest version 0.7.1.0 is showing up as deprecated on Hackage (https://hackage.haskell.org/package/logict/preferred) which means Cabal will not use it for satisfying builds.

**Comment by Bodigrim** [comment]
The reason for the deprecation was that the changes I made broke packages downstream, and I wanted to give them time to catch up. But given that 0.7.1.0 made way into Stackage LTS, it is probably a lesser evil to unhide it.

**Comment by kquick** [comment]
If it broke downstream, maybe leave 0.7.1.0 as deprecated and release it again under 0.8.0.0 to conform to PVP.  Then downstream packages with upper major constraint bounds should be fine as per normal PVP expectations.

**Comment by Bodigrim** [comment]
Unfortunately, it does not make much sense any longer: since `logict-0.7.10` made way into Stackage LTS (seems it does not check for deprecated status), its version is frozen there for a year or so. Having a package available for `stack` builds, but not for `cabal` ones would be bad in a long run. 

Practically speaking, downstream packages with upper bounds are unaffected. The only two broken packages do not have upper bounds and need to revise them anyways. They can put `< 0.7.1` as easily as `< 0.8`. I've contacted their maintainers three weeks ago.

All this is obviously caused by my fault and bad judgement, but given circumstances described above I'd rather leave it as is.

**Comment by kquick** [comment]
I wouldn't worry about the blame: it's easy to mis-calculate the impact when determining a new version, which is why the deprecated feature is nice.

I don't use stack so I wasn't aware of the nuance here, but I certainly understand the issue with it already being incorporated in the curated LTS.  I agree that in the circumstances it would be awkward to have two different active versions.

Thanks for removing the deprecation to enable it to be picked up by cabal operations!

**Comment by phadej** [comment]
I made revision to logict-0.7.1.0, hiding it. Stackage current and previous LTS are using 0.8, and `stack` will happily use 0.7.1.0 in snapshots, as it pins the revision (i.e. revisions doesn't affect old snapshots).
